### ISSUE TITLE
Improve queue.statistics()

### ISSUE THREAD

**Issue by subjrs** [tarantool/sharded-queue#12]
Helo!

Is it possible to do queue.statistics() function's output in "old style"?
In "old style" it showed all tubes stats and it showed them in yaml, like this:
```
unix/:/var/run/tarantool/r.control> queue.statistics()
---
- <tube_name>
    tasks:
      taken: 1
      done: 0
      ready: 0
      total: 1
      delayed: 0
      buried: 0
    calls:
      delete: 0
      ack: 0
      touch: 0
      take: 1
      kick: 0
      bury: 0
      put: 1
      release: 0
```

Now i must specify tube:
queue.statistics('tube_name'), and output is Lua table:
```
---
- {'tasks': {'taken': 1, 'done': 0, 'ready': 0, 'buried': 0, 'delayed': 0, 'total': 1},
  'calls': {'delete': 0, 'bury': 0, 'touch': 0, 'take': 1, 'kick': 0, 'release': 0,
    'put': 1, 'ack': 0}}
...
```
It's horrible to parse inside metric's collector and I don't know how to get list of tubes
